// All popup routes (transfer, swap, receive, select account, dapp requests, etc.) in one chunk,
// so moving between them after the first load is instant instead of a fresh suspend per route.
export { default as AccountSelectScreen } from '@web/modules/account-select/screens/AccountSelectScreen'
export { default as AddOrUpdateNetworkScreen } from '@web/modules/action-requests/screens/AddOrUpdateNetworkScreen'
export { default as BenzinScreen } from '@web/modules/action-requests/screens/BenzinScreen'
export { default as DappConnectScreen } from '@web/modules/action-requests/screens/DappConnectScreen'
export { default as DecryptRequestScreen } from '@web/modules/action-requests/screens/DecryptRequestScreen'
export { default as ExploreScreen } from '@web/modules/explore/screens/ExploreScreen'
export { default as ExploreSectionScreen } from '@web/modules/explore/screens/ExploreSectionScreen'
export { default as ExtensionRewardsScreen } from '@web/modules/extension-rewards/screens/ExtensionRewardsScreen'
export { default as GetEncryptionPublicKeyRequestScreen } from '@web/modules/action-requests/screens/GetEncryptionPublicKeyRequestScreen'
export { default as NetworksScreen } from '@web/modules/networks/screens'
export { default as ReceiveScreen } from '@web/modules/receive/screens/ReceiveScreen'
export { default as SignAccountOpScreen } from '@web/modules/sign-account-op/screens/SignAccountOpScreen'
export { default as SignMessageScreen } from '@web/modules/sign-message/screens/SignMessageScreen'
export { default as SurveyScreen } from '@web/modules/survey/screens/SurveyScreen/SurveyScreen'
export { default as SwapAndBridgeScreen } from '@web/modules/swap-and-bridge/screens/SwapAndBridgeScreen'
export { default as SwitchAccountScreen } from '@web/modules/action-requests/screens/SwitchAccountScreen'
export { default as TokenDetailsScreen } from '@web/modules/token-details/screens/TokenDetailsScreen'
export { default as TransferScreen } from '@web/modules/transfer/screens/TransferScreen'
export { default as WatchTokenRequestScreen } from '@web/modules/action-requests/screens/WatchTokenRequestScreen'
