import Fuse from 'fuse.js'
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useForm } from 'react-hook-form'
import { useTranslation } from 'react-i18next'
import { Platform, View } from 'react-native'
import { useModalize } from 'react-native-modalize'
import { WebView, WebViewNavigation } from 'react-native-webview'
import { useLocation } from 'react-router-native'

import { Dapp } from '@ambire-common/interfaces/dapp'
import GlobeIcon from '@common/assets/svg/GlobeIcon'
import GoogleIcon from '@common/assets/svg/GoogleIcon'
import BottomSheet from '@common/components/BottomSheet'
import Search from '@common/components/Search'
import Text from '@common/components/Text'
import { ControllersMiddlewareContext } from '@common/contexts/controllersMiddlewareContext'
import useController from '@common/hooks/useController'
import useDebounce from '@common/hooks/useDebounce'
import { AnimatedPressable, useCustomHover } from '@common/hooks/useHover'
import useTheme from '@common/hooks/useTheme'
import DappItem from '@common/modules/dapp-catalog/components/DappItem'
import eventBus from '@common/services/event/eventBus'
import spacings from '@common/styles/spacings'
import flexbox from '@common/styles/utils/flexbox'
import { WEBVIEW_DEV_HOST } from '@env'
import { MobileLayoutContainer } from '@mobile/components/MobileLayoutWrapper'
import DappRequestBottomSheet from '@mobile/modules/webview/components/DappRequestBottomSheet'
import DappWebViewFooter from '@mobile/modules/webview/components/DappWebViewFooter'

// The provider bundle is generated by webpack.webview.config.js
// @ts-ignore
const ambireInpageBundle = require('../../services/ambire-inpage-bundle.json')
// @ts-ignore
const ethereumInpageBundle = require('../../services/ethereum-inpage-bundle.json')

const securityPatches = `
  // 1. Redirect console to React Native for easy debugging
  (function() {
    var originalLog = console.log;
    var originalWarn = console.warn;
    var originalError = console.error;

    function sendToRN(type, args) {
      window.ReactNativeWebView.postMessage(JSON.stringify({
        type: 'log',
        logType: type,
        args: Array.from(args).map(arg => {
          try {
            return typeof arg === 'object' ? JSON.stringify(arg) : String(arg);
          } catch(e) {
            return String(arg);
          }
        })
      }));
    }

    console.log = function() {
      sendToRN('log', arguments);
      originalLog.apply(console, arguments);
    };
    console.warn = function() {
      sendToRN('warn', arguments);
      originalWarn.apply(console, arguments);
    };
    console.error = function() {
      sendToRN('error', arguments);
      originalError.apply(console, arguments);
    };
  })();

  // 2. Security: Block file:// access
  var _originalFetch = window.fetch;
  window.fetch = function() {
    var url = arguments[0];
    if (typeof url === 'string' && url.indexOf('file://') === 0) {
      return Promise.reject(new Error('fetch to file:// is blocked for security.'));
    }
    if (url && typeof url === 'object' && url.url && url.url.indexOf('file://') === 0) {
      return Promise.reject(new Error('fetch to file:// is blocked for security.'));
    }
    return _originalFetch.apply(this, arguments);
  };
  var _originalOpen = XMLHttpRequest.prototype.open;
  XMLHttpRequest.prototype.open = function(method, url) {
    if (typeof url === 'string' && url.indexOf('file://') === 0) {
      throw new Error('XHR to file:// is blocked for security.');
    }
    return _originalOpen.apply(this, arguments);
  };

  // 3. Verification: Check for providers
  window.addEventListener('load', function() {
    setTimeout(function() {
      console.log('[Ambire Verification] Checking providers...');
      var hasEthereum = !!window.ethereum;
      var hasAmbire = !!window.ambire;
      console.log('[Ambire Verification] window.ethereum present:', hasEthereum);
      console.log('[Ambire Verification] window.ambire present:', hasAmbire);

      if (hasEthereum && window.ethereum.request) {
        console.log('[Ambire Verification] Calling eth_chainId...');
        window.ethereum.request({ method: 'eth_chainId' })
          .then(function(id) { console.log('[Ambire Verification] eth_chainId result:', id); })
          .catch(function(err) { console.error('[Ambire Verification] eth_chainId error:', err); });
      }
    }, 2000);
  });

  window.onerror = function(msg, url, lineNo, columnNo, error) {
    var errStr = error ? (error.stack || error.message || String(error)) : msg;
    console.error('[Ambire window.onerror]', errStr, 'at', url, ':', lineNo, ':', columnNo);
    return false;
  };

  // 4. Hide dev error overlays (react-error-overlay, webpack-dev-server, Next.js dev)
  var s = document.createElement('style');
  s.textContent = '#__react-error-overlay__,iframe#webpack-dev-server-client-overlay,nextjs-portal{display:none!important}';
  (document.head || document.documentElement).appendChild(s);
`

const WEBVIEW_DEV_SERVER_PORT = 8082
const getDevServerUrl = () => {
  if (Platform.OS === 'android') {
    return `http://${WEBVIEW_DEV_HOST || '10.0.2.2'}:${WEBVIEW_DEV_SERVER_PORT}`
  }
  return `http://localhost:${WEBVIEW_DEV_SERVER_PORT}`
}

const DappWebViewScreen = () => {
  const [devAmbireCode, setDevAmbireCode] = useState<string | null>(null)
  const [devEthereumCode, setDevEthereumCode] = useState<string | null>(null)

  useEffect(() => {
    if (__DEV__) {
      Promise.all([
        fetch(`${getDevServerUrl()}/ambire-inpage-bundle.js`).then((res) => res.text()),
        fetch(`${getDevServerUrl()}/ethereum-inpage-bundle.js`).then((res) => res.text())
      ])
        .then(([ambireCode, ethereumCode]) => {
          setDevAmbireCode(ambireCode)
          setDevEthereumCode(ethereumCode)
        })
        .catch((err) => {
          console.warn('[Ambire] Failed to fetch inpage bundles from dev server', err)
        })
    }
  }, [])

  const { theme } = useTheme()
  const { t } = useTranslation()
  const location = useLocation()
  const { dispatch } = React.useContext(ControllersMiddlewareContext)
  const {
    state: { dapps },
    currentDapp,
    dappUrl,
    setDappUrl
  } = useController('DappsController')

  // Initial State from Route
  const initialUrl = (location.state as any)?.url || 'https://google.com'

  // WebView Refs & State
  const webviewRef = useRef<WebView>(null)
  const [currentUrl, setCurrentUrl] = useState<string>(initialUrl)
  const currentUrlRef = useRef<string>(initialUrl)
  const [canGoBack, setCanGoBack] = useState(false)

  useEffect(() => {
    if (!dappUrl && setDappUrl) setDappUrl(initialUrl)
  }, [dappUrl, initialUrl, setDappUrl])

  const activeDappUrl = dappUrl || initialUrl

  // Bottom Sheet & Search Form State
  const { ref: searchModalRef, open: openSearchModal, close: closeSearchModal } = useModalize()
  // Dapp Request Bottom Sheet State - from RequestsController helpers
  const { requestModalRef, closeRequestModal, onBottomSheetClosed } =
    useController('RequestsController')
  const { control: headerControl, setValue: setHeaderValue } = useForm({
    defaultValues: { search: initialUrl }
  })
  const {
    control: searchControl,
    watch: searchWatch,
    setValue: setSearchValue
  } = useForm({ defaultValues: { search: '' } })
  const bottomSheetSearchQuery = searchWatch('search')
  const debouncedSearch = useDebounce({ value: bottomSheetSearchQuery, delay: 350 })

  const searchHeaderComponent = useMemo(
    () => (
      <Search
        control={searchControl}
        placeholder={t('Search or enter URL')}
        autoFocus={true}
        containerStyle={spacings.mbLg}
      />
    ),
    [searchControl, t]
  )

  const { account } = useController('SelectedAccountController').state

  const smartAccountType = useMemo(() => {
    if (account?.creation) return 'Ambire'
    if (account?.safeCreation) return 'Safe'
    return undefined
  }, [account])

  const handleOpenSearchModal = useCallback(() => {
    setSearchValue('search', currentUrl)
    openSearchModal()
  }, [openSearchModal, setSearchValue, currentUrl])

  const handleGoBack = useCallback(() => {
    webviewRef.current?.goBack()
  }, [])

  const handleRefresh = useCallback(() => {
    webviewRef.current?.reload()
  }, [])

  const hostname = useMemo(() => {
    try {
      return new URL(currentUrl).hostname
    } catch {
      return currentUrl
    }
  }, [currentUrl])

  // Keep the Header placeholder in sync with current URL
  useEffect(() => {
    setHeaderValue('search', hostname)
  }, [hostname, setHeaderValue])

  const handleNavigationStateChange = useCallback(
    (e: WebViewNavigation) => {
      if (!e.loading) {
        try {
          const url = new URL(e.url)
          // Reject non-HTTPS protocols to prevent MITM attacks
          if (url.protocol !== 'https:') {
            console.warn('[DappWebView] Blocked navigation to non-HTTPS URL:', e.url)
            // For HTTP URLs, we could optionally redirect to HTTPS or show a warning
            // For now, we just don't update the current URL, keeping the previous safe URL
            return
          }
          const previousOrigin = currentUrlRef.current
          setCurrentUrl(e.url)
          currentUrlRef.current = e.url
          setCanGoBack(e.canGoBack)
          // Keep dappUrl in sync with the actual page the WebView is on so that
          // currentDapp (and the ManageApp bottom sheet) always reflect the real URL
          setDappUrl?.(e.url)
          // If the origin changed, delete the stale session so the next provider
          // request creates a fresh one bound to the new origin
          try {
            if (new URL(previousOrigin).origin !== url.origin) {
              dispatch({ type: 'WEBVIEW_ORIGIN_CHANGED', params: { previousOrigin } })
            }
          } catch {
            // previousOrigin may not be a valid URL yet (e.g. on first load)
          }
        } catch {
          console.warn('[DappWebView] Invalid URL in navigation:', e.url)
        }
      }
    },
    [dispatch, setDappUrl]
  )

  // ── Inpage Provider Injection ──
  const injectionScript = useMemo(() => {
    // Use the dynamically fetched dev code if available, fallback to bundled code
    const baseCodeAmbire = (__DEV__ && devAmbireCode) || ambireInpageBundle.code
    const baseCodeEthereum = (__DEV__ && devEthereumCode) || ethereumInpageBundle.code

    return `
      ${securityPatches}

      window.addEventListener('message', function(event) {
        // Log EVERY message for debugging
        console.log('[Ambire] [Bridge DEBUG] window message received:', typeof event.data === 'string' ? event.data : JSON.stringify(event.data));

        if (event.data && typeof event.data.topic === 'string' && (event.data.topic.indexOf('ambireProviderRequest') > -1 || event.data.topic.indexOf('ambireNextBuildProviderRequest') > -1)) {
          if (event.data.topic.indexOf('<') === 0) {
            // Ignore response messages sent from RN back to the injected provider.
            return;
          }
          console.log('[Ambire] [Bridge] Caught MATCHING message:', event.data.topic, event.data.payload ? event.data.payload.method : 'no-payload');
          if (window.ReactNativeWebView) {
            window.ReactNativeWebView.postMessage(JSON.stringify({
              type: 'providerRequest',
              payload: event.data.payload,
              id: event.data.id,
              topic: event.data.topic
            }));
          } else {
            console.error('[Ambire] [Bridge] window.ReactNativeWebView NOT FOUND');
          }
        }
      });

      (function() {
        try {
        console.log('[Ambire] injecting provider code');
          ${baseCodeAmbire}
          ${baseCodeEthereum}
          console.log('[Ambire] Provider code executed successfully');
        } catch(e) {
          console.error('[Ambire] Provider code CRASHED:', e && e.stack ? e.stack : (e && e.message ? e.message : String(e)));
        }

        console.log('[Ambire] window.ethereum:', !!window.ethereum, 'window.ambire:', !!window.ambire);
      })();
      true;
    `
  }, [devAmbireCode, devEthereumCode])

  // Dapp Search Data Filtering
  const searchableDapps = useMemo(
    () =>
      dapps.map((dapp: Dapp) => ({
        dapp,
        name: dapp.name.toLowerCase(),
        url: dapp.url.toLowerCase(),
        description: dapp.description?.toLowerCase() || ''
      })),
    [dapps]
  )

  const searchResults = useMemo(() => {
    if (!debouncedSearch) return []
    const fuse = new Fuse(searchableDapps, {
      keys: [
        { name: 'name', weight: 0.7 },
        { name: 'url', weight: 0.2 },
        { name: 'description', weight: 0.1 }
      ],
      shouldSort: false,
      threshold: 0.2, // matching DappCatalogScreen logic
      minMatchCharLength: 1
    })
    const results = fuse.search(debouncedSearch)
    return results.map((result) => result.item.dapp)
  }, [debouncedSearch, searchableDapps])

  const isValidUrl = (urlString: string) => {
    try {
      return Boolean(new URL(urlString))
    } catch {
      return false
    }
  }

  // Data to render in bottom sheet list
  const listData = useMemo(() => {
    const data: any[] = []
    if (debouncedSearch) {
      data.push({ type: 'googleSearch', query: debouncedSearch })
      if (isValidUrl(debouncedSearch)) {
        data.push({ type: 'openPage', query: debouncedSearch })
      }
    } else {
      const suggestedDapps = dapps.filter((dapp: Dapp) => dapp.favorite || dapp.isConnected)
      const emptySearchFallback = suggestedDapps.length > 0 ? suggestedDapps : dapps
      data.push(...emptySearchFallback.map((dapp: Dapp) => ({ type: 'dapp', dapp })))
    }
    data.push(...searchResults.map((dapp: Dapp) => ({ type: 'dapp', dapp })))
    return data
  }, [debouncedSearch, searchResults, dapps])

  const handleNavigateToUrl = useCallback(
    (url: string) => {
      setDappUrl?.(url)
      closeSearchModal()
    },
    [closeSearchModal, setDappUrl]
  )

  const renderSearchItem = useCallback(
    ({ item }: { item: any }) => {
      if (item.type === 'openPage') {
        return (
          <AnimatedPressable
            onPress={() => handleNavigateToUrl(item.query)}
            style={[flexbox.directionRow, flexbox.alignCenter, spacings.mb]}
          >
            <View
              style={[
                spacings.mrSm,
                flexbox.center,
                {
                  backgroundColor: theme.secondaryBackground,
                  borderRadius: 50,
                  width: 40,
                  height: 40
                }
              ]}
            >
              <GlobeIcon />
            </View>
            <Text weight="medium" appearance="secondaryText">
              Open "{item.query}"
            </Text>
          </AnimatedPressable>
        )
      }

      if (item.type === 'googleSearch') {
        return (
          <AnimatedPressable
            onPress={() =>
              handleNavigateToUrl(
                `https://www.google.com/search?q=${encodeURIComponent(item.query)}`
              )
            }
            style={[flexbox.directionRow, flexbox.alignCenter, spacings.mb]}
          >
            <View
              style={[
                spacings.mrSm,
                flexbox.center,
                {
                  backgroundColor: theme.secondaryBackground,
                  borderRadius: 50,
                  width: 40,
                  height: 40
                }
              ]}
            >
              <GoogleIcon />
            </View>
            <Text weight="medium" appearance="secondaryText">
              Search Google for "{item.query}"
            </Text>
          </AnimatedPressable>
        )
      }

      if (item.type === 'dapp') {
        return (
          <DappItem {...item.dapp} onPressOverride={() => handleNavigateToUrl(item.dapp.url)} />
        )
      }
      return null
    },
    [theme, handleNavigateToUrl]
  )

  const searchKeyExtractor = useCallback(
    (item: any, index: number) => (item.type === 'dapp' ? item.dapp.url : `google-${index}`),
    []
  )

  const searchFlatListProps = useMemo(
    () => ({
      contentContainerStyle: spacings.pbLg,
      data: listData,
      renderItem: renderSearchItem,
      keyExtractor: searchKeyExtractor,
      keyboardShouldPersistTaps: 'handled' as const
    }),
    [listData, renderSearchItem, searchKeyExtractor]
  )

  const handleMessage = useCallback(
    (event: any) => {
      try {
        const data = JSON.parse(event.nativeEvent.data)
        console.log(
          '[DappWebView] RN received message type:',
          data.type || (data.method ? 'raw-provider-request' : 'unknown')
        )
        if (data.type === 'log') {
          const prefix = `[WebView ${data.logType}]`
          // eslint-disable-next-line no-console
          console.log(prefix, ...data.args)
        } else if (data.type === 'providerRequest' || (data.method && data.id)) {
          const method = data.type === 'providerRequest' ? data.payload?.method : data.method
          console.log('[DappWebView] Received providerRequest:', method, data.id)

          const payload =
            data.type === 'providerRequest'
              ? data.payload
              : { method: data.method, params: data.params }
          const topic = data.topic || '> ambireProviderRequest'

          // Store the expected origin when request is received to detect navigation during async operations
          const expectedOrigin = (() => {
            try {
              return new URL(currentUrlRef.current).origin
            } catch {
              return null
            }
          })()
          if (expectedOrigin && data.id) {
            requestOriginsRef.current[data.id] = expectedOrigin
          }

          dispatch({
            type: 'HANDLE_PROVIDER_REQUEST',
            params: {
              request: { ...payload, origin: currentUrlRef.current },
              requestId: data.id,
              providerId: 1,
              topic
            }
          })
        }
      } catch (e) {
        // Ignore non-JSON or other messages
      }
    },
    [dispatch]
  )

  // Track the URL at the time of each request to detect navigation during async operations
  const requestOriginsRef = useRef<Record<string, string>>({})

  useEffect(() => {
    const onProviderResponse = (data: any) => {
      console.log(
        '[DappWebView] Sending response back to WebView:',
        data.requestId,
        data.result ? 'SUCCESS' : 'ERROR/NULL'
      )

      // Fix 5: Verify the WebView hasn't navigated to a different origin during the async operation
      const expectedOrigin = requestOriginsRef.current[data.requestId]
      if (expectedOrigin) {
        delete requestOriginsRef.current[data.requestId]
      }

      const replyMessage = {
        topic: data.topic ? data.topic.replace('>', '<') : '< ambireProviderRequest',
        payload: { response: data.result, error: data.error },
        id: data.requestId
      }

      // Fix 2: Include origin check in injected script to prevent message interception
      // A malicious page could navigate here between request and response; this check prevents it from receiving the response
      webviewRef.current?.injectJavaScript(`
         (function() {
           if (${JSON.stringify(expectedOrigin)} && location.origin !== ${JSON.stringify(expectedOrigin)}) {
             console.warn('[Ambire] Response blocked: origin mismatch. Expected:', ${JSON.stringify(expectedOrigin)}, 'Got:', location.origin);
             return;
           }
           window.postMessage(${JSON.stringify(replyMessage)}, '*');
         })();
         true;
       `)
    }
    eventBus.addEventListener('action.sendToDappWebView', onProviderResponse)
    return () => eventBus.removeEventListener('action.sendToDappWebView', onProviderResponse)
  }, [])

  useEffect(() => {
    const onBroadcastDappEvent = (data: any) => {
      const { event, data: eventData } = data
      webviewRef.current?.injectJavaScript(`
        (function() {
          if (window.__ambire_handleEvent) {
            window.__ambire_handleEvent(${JSON.stringify(event)}, ${JSON.stringify(eventData ?? null)});
          }
        })();
        true;
      `)
    }
    eventBus.addEventListener('action.broadcastDappEvent', onBroadcastDappEvent)
    return () => eventBus.removeEventListener('action.broadcastDappEvent', onBroadcastDappEvent)
  }, [])

  return (
    <MobileLayoutContainer
      footer={
        <DappWebViewFooter
          headerControl={headerControl}
          handleOpenSearchModal={handleOpenSearchModal}
          handleGoBack={handleGoBack}
          canGoBack={canGoBack}
          handleRefresh={handleRefresh}
          account={account}
          currentDapp={currentDapp}
          smartAccountType={smartAccountType}
        />
      }
    >
      <View style={flexbox.flex1}>
        <WebView
          ref={webviewRef}
          source={{ uri: activeDappUrl }}
          onNavigationStateChange={handleNavigationStateChange}
          injectedJavaScriptBeforeContentLoaded={injectionScript}
          onMessage={handleMessage}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          allowFileAccessFromFileURLs={false}
          allowUniversalAccessFromFileURLs={false}
          originWhitelist={['https://*']}
        />
      </View>

      <BottomSheet
        id="dapp-webview-search"
        sheetRef={searchModalRef}
        adjustToContentHeight={false}
        closeBottomSheet={closeSearchModal}
        HeaderComponent={searchHeaderComponent}
        flatListProps={searchFlatListProps}
      />

      <DappRequestBottomSheet
        sheetRef={requestModalRef as any}
        closeBottomSheet={closeRequestModal as any}
        onClosed={onBottomSheetClosed as any}
      />
    </MobileLayoutContainer>
  )
}

export default DappWebViewScreen
