import { buildSelector } from '@helpers/buildSelector'

// TODO: this should be refactored; we should have single file with selector IDs
const selectors = {
  getStarted: {
    createNewAccountButton: 'create-new-account-btn',
    createRecoveryPhraseButton: 'review-seed-phrase-btn',
    importAccountButton: 'button-import-account',
    confirmationMessageForViewOnly: 'added-successfully-text',
    confirmationMessageAmbireWallet: 'wallet-ready-to-use-text',
    savedPhraseButton: 'create-seed-phrase-write-continue-btn',
    recoveryPhraseHeader: 'back-up-recovery-phrase-text',
    copyRecoveryPhraseButton: 'copy-recovery-phrase',
    recoveryPhraseCopiedSnackbar: 'success-0', // first snackbar that appears has value 0 after dash
    checkbox: 'checkbox',
    enterPassField: 'enter-pass-field',
    repeatPassField: 'repeat-pass-field',
    createKeystorePassBtn: 'create-keystore-pass-btn',
    watchAddress: 'watch-an-address-button',
    addMoreAccountsButton: 'add-more-accounts-btn',
    addOneMoreAddress: 'add-one-more-address',
    importExistingAccBtn: 'import-existing-account-btn',
    importMethodPrivateBtn: 'import-method-private-key',
    importMethodRecoveryPhrase: 'import-method-recovery-phrase',
    importMethodJSON: 'import-method-json-backup-file',
    enterSeedPhraseField: 'enter-seed-phrase-field',
    enterPrivateKeyField: 'enter-private-key-field',
    advancedPassPhraseSwitch: 'enable-passphrase-toggle',
    recoveryPhrasePassphraseField: 'input-passphrase',
    warningCheckbox: 'backup-warning-checkbox',
    addressEnsField: 'address-ens-field',
    showMoreBtn: 'show-more-btn',
    viewOnlyBtnImport: 'view-only-button-import',
    importBtn: 'import-button',
    openDashboardButton: 'onboarding-completed-open-dashboard-btn',
    editFirstAccNameButton: 'edit-btn-for-edit-name-field-0', // same id used for clearing input field; after edit for checking confirmation pill 'Save'
    editAccountNameInputField: 'edit-name-field-0',
    saveAndContinueBtn: 'button-save-and-continue',
    hdPathLegerLive: 'hd-path-option-ledger-live',
    changeHDPathButton: 'change-hd-path-btn',
    hdPathConfirmButton: 'hd-path-confirm-btn',
    hdPathLegerLegacy: 'hd-path-option-ledger-legacy',
    smartAccountPicker: 'add-account-' // need add index 5
  },
  dashboard: {
    tokensTabButton: 'tokens-defi',
    noTokensText: 'no-tokens-text',
    tokenTitleText: '[data-testid^="token-balance-"]',
    nftTabButton: 'tab-nft',
    noCollectiblesText: 'no-collectibles-text',
    defiTabButton: 'tab-defi',
    noProtocolsText: 'no-protocols-text',
    suggestProtocolText: 'suggest-protocol-text',
    openTicketLink: 'open-ticket-link',
    activityTabButton: 'tab-activity',
    viewTransactionLink: 'view-transaction-link',
    sendButton: 'dashboard-button-send',
    swapAndBridgeButton: 'dashboard-button-swap-and-bridge',
    hamburgerButton: 'dashboard-hamburger-btn',
    balanceErrorIcon: 'balance-affecting-error-icon',
    portfolioErrorAlert: 'portfolio-error-alert',
    noTransactionOnActivityTab: 'no-transaction-history-text',
    transactionSendText: '(//div[contains(text(),"Send")])[2]', // TODO: change once we have id on FE
    confirmedTransactionPill: '//div[contains(text(),"Confirmed")]', // TODO: chage once we have id on FE
    fuelGasTankTransactionPill: '//div[contains(text(),"Fuel gas tank with")]', // TODO: chage once we have id on FE,
    grantApprovalText: '//div[contains(text(),"Grant approval")]', // TODO: change once we have id on FE,
    networksDropdown: 'networks-dropdown',
    magnifyingGlassIcon: 'search-glass-icon',
    tokenBalance: '[data-testid^="token-balance"]',
    networkBase: '//div[text()="Base"]',
    nftTitle: 'collection-item',
    nftsTitle: '[data-testid^="collection-item"]',
    searchForNetwork: 'search-for-network-field',
    hideTokenButton: 'hide-token-button',
    yesHideItButton: 'yes-hide-it-text',
    hideTokenModalTitle: 'hide-token-modal-title',
    hideTokenModalDescription: 'hide-token-modal-description',
    rewardsButton: 'dashboard-button-quests',
    projectedRewardsButton: 'rewards-button',
    backRewardsButton: '//div[contains(text(),"Back")]',
    rewardsLink: '//div[contains(text(),"Ambire Rewards")]',
    projectedRewardsClaimButton: 'projected-rewards-claim-button'
  },
  settings: {
    createNewRecoveryPhraseButton: 'create-new-recovery-phrase',
    importAccountButton: 'import-account',
    connectHardwareWallet: 'connect-hardware-wallet',
    watchAnAddressButton: 'watch-an-address-button',
    viewOnlyAddressField: 'address-ens-field',
    viewOnlyImportButton: 'view-only-button-import',
    validENSDomainText: '//div[contains(text(),"Valid ENS domain")]',
    addedSuccessfullyText: '//div[contains(text(),"Added successfully")]',
    accessAccFromDashboardInfoText: '//div[contains(text(),"access your accounts")]',
    addAccountButton: 'add-account-modal',
    hiddenTokenName: 'hidden-token-name', // works for custom tokens section
    hiddenTokenNetwork: 'hidden-token-network', // works for custom tokens section
    unhideTokenButton: 'unhide-button',
    youDontHaveInfoText: 'you-dont-have-any-text', // there can be multiple on same page
    customTokens: {
      addCustomTokenButton: 'add-custom-token-button',
      addTokenModalTitle: 'add-token-modal-title-text',
      ethNetworkOption: 'option-Ethereum',
      opMainnetNetworkOption: 'option-OP-Mainnet',
      bnbNetworkOption: 'option-BNB-Chain',
      polygonNetworkOption: 'option-Polygon',
      mantleNetworkOption: 'option-Mantle',
      baseNetworkOption: 'option-Base',
      arbitrumNetworkOption: 'option-Arbitrum',
      tokenAddressField: 'token-address-field',
      customNameTokenText: 'custom-token-name', // visible after entering valid address
      confirmedPillText: 'confirmed-pill-text',
      addTokenButton: 'add-token-button',
      addedTokenSnackbar: '//span[contains(text(),"Added token")]',
      tokenRemovedSnackbar: '//span[contains(text(),"Token removed")]',
      removeCustomTokenButton: 'remove-button'
    }
  },
  transaction: {
    feeTokensSelectDropdown: 'fee-option-select',
    feeSpeedSelectDropdown: 'fee-speed-select',
    feeSpeedSlow: 'option-slow',
    feeSpeedMedium: 'option-medium',
    feeSpeedFast: 'option-fast',
    feeSpeedApe: 'option-ape',
    feeGasTankInDollars: '//span[contains(text(),"Gas Tank")]/../../../div[contains(text(),"$")]', // returning e.g. "<$0.01"
    feeTokenInDollars: '//span[contains(text(),"")]/../../div[contains(text(),"$")]',
    confirmingYourTransactionText: '//div[contains(text(),"Confirming your")]',
    explorer: {
      txnSignedStep: 'signed-step',
      txnProgressStep: 'txn-progress-step',
      txnConfirmedStep: 'finalized-rows',
      recepientAddressBlock: 'recipient-address-undefined'
    }
  },
  // TODO: update selectors wiyh testID
  ambireRewards: {
    connectAmbireButton: '//button[contains(text(),"Connect Ambire")]',
    claimRewardButton: '//button[contains(text(),"Claim")]',
    readAnnouncementHyperlink: '//a[contains(@href, "rewards-enters")]',
    faqFirstQuestion: '//span[contains(text(),"What is Ambire")]',
    faqFirstAnswer: '(//div/p)[2]',
    faqSecondQuestion: '//span[contains(text(),"Is Ambire")]',
    faqSecondAnswer: '(//div/p)[3]',
    faqThirdQuestion: '//span[contains(text(),"Can I participate with a wallet")]',
    faqThirdAnswer: '(//div/p)[4]',
    faqFourthQuestion: '//span[contains(text(),"Which tokens")]',
    faqFourthAnswer: '(//div/p)[5]',
    faqFifthQuestion: '//span[contains(text(),"How is Swap&Bridge")]',
    faqFifthAnswer: '(//div/p)[6]',
    faqSixthQuestion: '//span[contains(text(),"Can I use my")]',
    faqSixthAnswer: '(//div/p)[7]',
    faqSeventhQuestion: '//span[contains(text(),"Can I participate with multiple")]',
    faqSeventhAnswer: '(//div/p)[8]',
    faqEightQuestion: '//span[contains(text(),"How long is the current")]',
    faqEightAnswer: '(//div/p)[9]',
    faqNinthQuestion: '//span[contains(text(),"What are projected")]',
    faqNinthAnswer: '(//div/p)[10]',
    pageTitle: '//h1',
    pageDescription: '//p',
    homePage: '//span[contains(text(),"Home")]',
    leaderboardPage: '//span[contains(text(),"Leaderboard")]',
    rewardsPoolPage: '//span[contains(text(),"Rewards Pool")]',
    walletPage: '//span[contains(text(),"WALLET")]',
    faqPage: '//span[contains(text(),"FAQ")]'
  },
  account: 'account',
  importMethodTrezor: 'import-method-trezor',
  trezorConnectConfirmTerms: '@analytics/continue-button',
  buttonProceedSeedPhrase: 'button-proceed-seed-phrase',
  doNotSaveSeedBtn: 'do-not-save-seed-button',
  saveAsDefaultSeedBtn: 'save-seed-button',
  getStartedBtnImport: 'get-started-button-import',
  keystoreBtnCreate: 'keystore-button-create',
  keystoreBtnContinue: 'keystore-button-continue',
  editBtnForEditNameField: 'edit-btn-for-edit-name-field',
  editFieldNameField: 'edit-name-field',
  getStartedBtnAdd: 'get-started-button-add',
  addToAddressBookButton: 'add-to-address-book-button',
  addContactFormButton: 'add-contact-form-modal',
  contactNameField: 'contact-name-field',
  contactNameText: 'contact-name-text', // TODO: selector could be more precise
  contactAddressText: 'address',
  sendFormAddToAddresBook: 'send-form-add-to-address-book-button',
  formAddContactNameField: 'form-contact-name-field',
  formAddToContactsButton: 'form-add-to-contacts-button',
  buttonAddAccount: 'button-add-account',
  checkbox: 'checkbox',
  addAccount: 'add-account',
  seedPhraseInputFieldDynamic: 'seed-phrase-field',
  getStartedCreateHotWallet: 'get-started-create-hot-wallet',
  setUpWithSeedPhraseBtn: 'set-up-with-seed-phrase-btn',
  createSeedPrepareCheckboxDyn: 'create-seed-prepare-checkbox',
  reviewSeedPhraseBtn: 'review-seed-phrase-btn',
  recoveryWithSeedWordDyn: 'recovery-with-seed-word',
  createSeedPhraseWriteContinueBtn: 'create-seed-phrase-write-continue-btn',
  seedWordNumberToBeEntered: 'seed-word-number-to-be-entered',
  seedWordPositionFieldDyn: 'seed-word-position-field',
  createSeedPhraseConfirmContinueBtn: 'create-seed-phrase-confirm-continue-btn',
  personalizeAccount: 'personalize-account',
  pinExtensionCloseBtn: 'pin-extension-close-btn',
  accountSelectBtn: 'account-select-btn',
  selectSeedPhraseLength: 'select-seed-phrase-length',
  option24WordsSeedPhrase: 'option-i-have-24-word-phrase',
  selectChangeHdPath: 'select-change-hd-path',
  optionBip44LedgerLive: 'option-bip44-ledger-live',
  importExistingWallet: 'import-existing-wallet',
  optionLegacyLedgerMyEtherWalletMyCrypto: 'option-legacy-ledger-myetherwallet-mycrypto',
  getStartedButtonConnectHwWallet: 'get-started-button-connect-hw-wallet',
  selectHwOptionTrezor: 'select-hw-option-trezor',
  trezorPermissionConfirmButton: '@permissions/confirm-button',
  trezorExportAddressConfirmButton: '@export-address/confirm-button',
  enterCurrentPassField: 'enter-current-pass-field',
  enterNewPassField: 'enter-new-pass-field',
  repeatNewPassField: 'repeat-new-pass-field',
  changeDevicePassButton: 'change-device-pass-button',
  bottomSheet: 'bottom-sheet',
  devicePassSuccessModal: 'device-pass-success-modal',
  lockExtensionButton: 'lock-extension-button',
  passphraseField: 'passphrase-field',
  buttonUnlock: 'button-unlock',
  fullBalance: 'full-balance',
  tabNft: 'tab-nft',
  collectionItem: 'collection-item',
  collectiblePicture: 'collectible-picture',
  collectibleRow: 'collectible-row',
  addressBookMyWalletContactDyn: 'address-book-my-wallet-contact',
  continueAnywayCheckboxSaB: 'checkbox',
  continueAnywayButton: '//div[contains(text(),"Continue anyway")]',
  amountField: 'amount-field',
  transferButtonConfirm: 'transfer-button-confirm',
  addAccountField: 'add-account-field',
  importExistingSeedBtn: 'import-existing-seed-btn',
  createSeedBtn: 'create-seed-btn',
  importFromSavedSeed: 'import-from-saved-seed',
  nativeTokenPolygonDyn: 'token-0x0000000000000000000000000000000000000000-polygon',
  tokenSend: 'token-send',
  tokensSelect: 'tokens-select',
  queueAndSignLaterButton: 'queue-and-sign-later-button',
  deleteTxnCallDyn: 'delete-txn-call',
  feeSlow: 'option-slow',
  feeMedium: 'option-medium',
  feeFast: 'option-fast',
  feeApe: 'option-ape',
  transactionButtonReject: 'transaction-button-reject',
  totalPortfolioAmountInteger: 'total-portfolio-amount-integer',
  proceedBtn: 'proceed-btn',
  batchBtn: 'batch-btn',
  privateKeyWarningCheckbox1: 'private-key-warning-checkbox-1',
  privateKeyWarningCheckbox2: 'private-key-warning-checkbox-2',
  nativeTokenBaseDashboard: 'token-0x0000000000000000000000000000000000000000-8453',
  bannerButtonOpen: 'banner-button-open',
  bannerButtonReject: 'banner-button-reject',
  confettiModalActionButton: 'confetti-modal-action-button',
  refreshButton: 'refresh-button',
  dashboardGasTankButton: 'dashboard-gas-tank-button',
  dashboardGasTankBalance: 'dashboard-gas-tank-balance',
  createSmartAccountGasTankModalButton: 'create-smart-account-gas-tank-modal-button',
  recieveNetworkBase: 'option-8453',
  recieveNetworkOptimism: 'option-10',
  confirmFollowUpTxn: 'confirm-follow-up-txns-checkbox',
  USDC: 'option-0x0b2c639c533813f4aa9d7837caf62653d097ff85.usdc',
  signTransactionButton: 'transaction-button-sign',
  maxAvailableAmount: 'max-available-amount',
  searchInput: 'search-input',
  // Swap & Bridge selectors
  sendTokenSab: 'from-token-select',
  receiveTokenSab: 'to-token-select',
  selectRouteButton: 'select-route',
  routeLoadingTextSab: 'route-loading-text-sab',
  fromAmountInputSab: 'from-amount-input-sab',
  switchTokensTooltipSab: 'switch-tokens-condition-tooltip-sab',
  switchCurrencySab: 'switch-currency-sab',
  routePrioritySab: 'route-priority-sab',
  sushiSwapRoute: 'div:has-text("SushiSwap Aggregator")',
  highPriceImpactSab: '//div[contains(text(), "Very high price impact")]', // TODO: change with ID when we add it
  highSlippageModal: '//div[contains(text(), "higher slippage")]', // TODO: change with ID when we add it
  settingsAddNetworkManually: 'add-network-manually',
  settingsAddNetworkFromChainlist: 'add-network-from-chainlist',
  removeNetworkButton: 'remove-network-btn',
  removeNetworkConfirmButton: 'remove-network-confirm-btn',
  signButton: 'sign-button',
  backButton: 'back-button',
  submitButton: 'button-submit',
  txnStatus: 'txn-status',
  batchModalGotIt: 'queue-modal-got-it-button',
  signButtonSwap: 'swap-button-sign',
  addMoreButton: 'add-more-button',
  flipIcon: 'flip-icon',
  swapSignButton: 'swap-button-sign',
  addToBatchButton: 'batch-btn',
  goDashboardButton: 'go-dashboard-button',
  txnConfirmed: 'txn-confirmed',
  maxAmountButton: 'max-amount-button',
  transactionConfirmedText: 'transaction-confirmed-text',
  closeTransactionProgressPopUpButton: '//div[contains(text(),"Close")]',
  // Top up
  modalGasTankBalance: 'gas-tank-balance',
  topUpButton: 'top-up-gas-tank-modal-button',
  closeProgressModalButton: 'track-progress-primary-button',
  // Network Management
  // TODO: change once we have IDs on FE
  disableNetworkButton: 'disable-network-btn',
  disableNetworkConfirmButton: 'disable-network-confirm-btn',
  addRPCURLButton: '//div[.//div[text()="RPC URL"]]//div[text()="Add"]',
  addNetworkButton: '//div[.//div[text()="Network details"]]//div[text()="Add network"]',
  connectWalletButton:
    "//div[.//span[text()='Include Testnets']]//button[normalize-space()='Connect Wallet']",
  chainlistSearchPlaceholder: 'input[placeholder*="ETH"]',
  addToMetamaskButton: '//button[contains(text(),"Add to Metamask")]',
  confirmaddNetworkOnChainlistButton: '//div[contains(text(),"Add network")]',
  blockExplorerURL: (url: string) => `//div[contains(text(),"${url}")]`,
  networkDetailEditButton: '//div[.//div[text()="Network details"]]//div[text()="Edit"]',
  // edit network modal
  editNetworkModalTitle: '//div[text()="Edit network"]',
  editNetworkCancelButton: '//div[contains(text(),"Cancel")]',
  editNetworkSaveButton: '//div[contains(text(),"Save")]',
  networkSettingsSavedSnackbar: (networkName: string) =>
    `((//div[contains(normalize-space(), "${networkName} settings saved!")]))[4]`, // TODO: snackbar selector finding 8 elements; change once we have ID on FE
  // Sign
  dappConnectButton: 'dapp-connect-button',
  dappSecurityCheckPassed: 'dapp-security-check-passed',
  signMessageButton: 'button-sign',
  // Notifications
  networkSuccessfullyAddedSnackbar:
    '(//div[contains(normalize-space(), "Network successfully added!")])[4]', // TODO: snackbar selector finding 8 elements; change once we have ID on FE
  contactSuccessfullyAddedSnackbar:
    '(//div[contains(normalize-space(), "Contact added to Address Book")])[4]' // TODO: snackbar selector finding 8 elements; change once we have ID on FE
}

type SelectorKey = keyof typeof selectors
type Selectors = { [K in SelectorKey]?: string }

export const SELECTORS: Selectors = Object.fromEntries(
  Object.entries(selectors).map(([key, value]) => [key, buildSelector(value)])
)

export default selectors
