name: "Setup environment"
runs:
  using: "composite"
  steps:
    - name: Install Node.js ⚙️
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
      shell: bash

    - name: Cache node modules
      id: cache-yarn
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: $ {{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-build-${{ env.cache-name }}\-${{ hashFiles('**/yarn.lock') }}
        restore-keys:
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - if: ${{ steps.cache-yarn.outputs.cache-hit != 'true' }}
      name: List the state of node modules
      continue-on-error: true
      run: yarn list
      shell: bash

    - name: Install NPM packages ♾️🕳️
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      run: yarn install
      shell: bash

    - name: Git submodules init
      run: git submodule init
      shell: bash

    - name: Git submodules update
      run: git submodule update
      shell: bash
