name: Benzin 🔥

on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2
permissions:
  contents: write
jobs:
  build:
    name: Build & Deploy Standalone Benzin
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    environment: benzin
    steps:
      - name: Add SSH key to checkout a private repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Checkout code 🛎️
        uses: actions/checkout@v5

      - name: Git submodules init
        run: git submodule init
        shell: bash

      - name: Git submodules update
        run: git submodule update
        shell: bash

      - name: Install Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        shell: bash

      - name: Build project 🛠️
        env:
          REACT_APP_PIMLICO_API_KEY: ${{ vars.REACT_APP_PIMLICO_API_KEY }}
          REACT_APP_ETHERSPOT_API_KEY: ${{ vars.REACT_APP_ETHERSPOT_API_KEY }}
          REACT_APP_CANDIDE_API_KEY: ${{ vars.REACT_APP_CANDIDE_API_KEY }}
          RELAYER_URL: ${{ vars.RELAYER_URL }}
        run: yarn build:web:benzin

      - name: Deploy 🚀🌕
        if: github.ref == 'refs/heads/v2'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: build/benzin-prod
          cname: explorer.ambire.com
