name: Legends 👾

on:
  push:
    branches:
      - legends-deploy-test
  pull_request:
    branches:
      - legends-deploy-test
permissions:
  contents: write
jobs:
  build:
    name: Build & Deploy Standalone Legends
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Add SSH key to chekout a private repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Checkout code 🛎️
        uses: actions/checkout@v3

      - name: Install Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Git submodules init
        run: git submodule init

      - name: Git submodules update
        run: git submodule update

      - name: Install Yarn packages ♾️🕳️
        run: yarn install

      - name: Build project 🛠️
        run: yarn build:web:legends

      - name: Deploy to Legends Repo gh-pages 🚀🌕
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git init
          git remote add origin https://x-access-token:${{ secrets.LEGENDS_DEPLOY_KEY }}@github.com/AmbireTech/legends-gh-pages.git
          git fetch origin
          git checkout gh-pages
          cp -R ./build/legends-prod/* .  # Copy your build output to the root of the branch
          git add .
          git commit -m "Deploy from ambire-app to legends-gh-pages"
          git push origin gh-pages
