name: Legends 👾
env:
  APP_ENV: production

on:
  push:
    branches:
      - legends-prod
permissions:
  contents: write
jobs:
  build:
    environment: legends
    name: Build & Deploy Standalone Legends
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Add SSH key to chekout a private repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Checkout code 🛎️
        uses: actions/checkout@v4

      - name: Git submodules init
        run: git submodule init
        shell: bash

      - name: Git submodules update
        run: git submodule update
        shell: bash

      - name: Install Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        shell: bash

      - name: Build project 🛠️
        env:
          RELAYER_URL: 'https://relayer.ambire.com'
          LEGENDS_NFT_ADDRESS: ${{ vars.LEGENDS_NFT_ADDRESS }}
          SENTRY_DSN_LEGENDS: ${{ vars.SENTRY_DSN_LEGENDS }}
        run: yarn build:web:legends

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.LEGENDS_DEPLOY_KEY }}

      - name: Upload source maps to Sentry
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          curl -sL https://sentry.io/get-cli/ | bash
          VERSION=$(node -p "require('./src/ambire-common/package.json').version")
          sentry-cli sourcemaps inject ./build/legends-prod
          sentry-cli releases new legends@$VERSION --project legends
          sentry-cli releases files legends@$VERSION upload-sourcemaps ./build/legends-prod/ --ext .js --ext .map --rewrite --project legends
          sentry-cli releases finalize legends@$VERSION --project legends

      - name: Deploy to Legends Repo gh-pages 🚀🌕
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone git@github.com:AmbireTech/legends-gh-pages.git legends-gh-pages
          cd legends-gh-pages
          git checkout gh-pages
          cp -R ../build/legends-prod/* .
          date > deployDate
          git add .
          git commit -m "Automated deploy from ambire-app"
          git push origin gh-pages --force
