name: Legends 👾

on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2
permissions:
  contents: write
jobs:
  build:
    name: Build & Deploy Standalone Legends
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Add SSH key to chekout a private repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Checkout code 🛎️
        uses: actions/checkout@v3

      - name: Install Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Git submodules init
        run: git submodule init

      - name: Git submodules update
        run: git submodule update

      - name: Install Yarn packages ♾️🕳️
        run: yarn install

      - name: Build project 🛠️
        run: yarn build:web:legends

      - name: Deploy 🚀🌕
        if: github.ref == 'refs/heads/v2'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: build/legends-prod
          cname: legends.ambire.com
