name: Browser Extension

on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout code 🛎️
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./github/workflows/setup.yml

      - name: Run Unit Tests
        run: yarn test
  e2e_tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    environment: testing
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout code 🛎️
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./github/workflows/setup.yml

        # The next step is required to run Puppeteer in headful mode in GitHub Actions.
        # We attempted to configure it in a headless manner,
        # but it fails right from the start when we attempt to locate the current page of the extension.
      - name: Configure the display server
        run: Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &

      - name: Puppeteer Tests 🧑‍🔬
        env:
          IS_TESTING: 'true'
          E2E_DEBUG: ${{ vars.E2E_DEBUG }}
          # Its value is based on the above Display server configuration
          DISPLAY: ':99.0'
          RELAYER_URL: ${{ vars.RELAYER_URL }}
          VELCRO_URL: ${{ vars.VELCRO_URL }}
          BROWSER_EXTENSION_DEFAULT_LOG_LEVEL_PROD: ${{ vars.BROWSER_EXTENSION_DEFAULT_LOG_LEVEL_PROD }}
          BROWSER_EXTENSION_DEFAULT_LOG_LEVEL_DEV: ${{ vars.BROWSER_EXTENSION_DEFAULT_LOG_LEVEL_DEV }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          SEED: ${{ secrets.SEED }}
          BA_PRIVATE_KEY: ${{ secrets.BA_PRIVATE_KEY }}
          BA_PASSPHRASE: ${{ secrets.BA_PASSPHRASE }}
          BA_ACCOUNT_PREFERENCES: ${{ vars.BA_ACCOUNT_PREFERENCES }}
          BA_ACCOUNTS: ${{ vars.BA_ACCOUNTS }}
          BA_IS_DEFAULT_WALLET: ${{ vars.BA_IS_DEFAULT_WALLET }}
          BA_KEY_PREFERENCES: ${{ vars.BA_KEY_PREFERENCES }}
          BA_KEYSTORE_UID: ${{ vars.BA_KEYSTORE_UID }}
          BA_KEYS: ${{ vars.BA_KEYS }}
          BA_SECRETS: ${{ secrets.BA_SECRETS }}
          BA_NETWORK_PREFERENCES: ${{ vars.BA_NETWORK_PREFERENCES }}
          BA_NETWORK_WITH_ASSETS: ${{ vars.BA_NETWORK_WITH_ASSETS }}
          BA_ONBOARDING_STATE: ${{ vars.BA_ONBOARDING_STATE }}
          BA_PERMISSION: ${{ vars.BA_PERMISSION }}
          BA_PREVIOUSHINTS: ${{ vars.BA_PREVIOUSHINTS }}
          BA_SELECTED_ACCOUNT: ${{ vars.BA_SELECTED_ACCOUNT }}
          BA_TERMSTATE: ${{ vars.BA_TERMSTATE }}
          BA_TOKEN_ITEMS: ${{ vars.BA_TOKEN_ITEMS }}
          SA_ACCOUNT_PREFERENCES: ${{ vars.SA_ACCOUNT_PREFERENCES }}
          SA_ACCOUNTS: ${{ vars.SA_ACCOUNTS }}
          SA_IS_DEFAULT_WALLET: ${{ vars.SA_IS_DEFAULT_WALLET }}
          SA_IS_ONBOARDED: ${{ vars.SA_IS_ONBOARDED }}
          SA_KEY_PREFERENCES: ${{ vars.SA_KEY_PREFERENCES }}
          SA_KEYSTORE_UID: ${{ vars.SA_KEYSTORE_UID }}
          SA_KEYS: ${{ vars.SA_KEYS }}
          SA_SECRETS: ${{ secrets.SA_SECRETS }}
          SA_NETWORK_PREFERENCES: ${{ vars.SA_NETWORK_PREFERENCES }}
          SA_ONBOARDING_STATE: ${{ vars.SA_ONBOARDING_STATE }}
          SA_PERMISSION: ${{ vars.SA_PERMISSION }}
          SA_PREVIOUSHINTS: ${{ vars.SA_PREVIOUSHINTS }}
          SA_SELECTED_ACCOUNT: ${{ vars.SA_SELECTED_ACCOUNT }}
          SA_TERMSTATE: ${{ vars.SA_TERMSTATE }}
          SA_TOKEN_ITEMS: ${{ vars.SA_TOKEN_ITEMS }}
          SA_NETWORK_WITH_ASSETS: ${{ vars.SA_NETWORK_WITH_ASSETS }}
          SA_PASSPHRASE: ${{ secrets.SA_PASSPHRASE }}
          DEFAULT_INVITATION_CODE_DEV: ${{ vars.DEFAULT_INVITATION_CODE_DEV }}

        run: yarn run test:e2e:web

        # Upload the recorded test videos (in case of failure) as Artifact
      - name: Artifacts - Recordings
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: puppeteer-recordings
          path: recorder