name: Execute Tests

on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    environment: testing
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Add SSH key to checkout a private repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Checkout code 🛎️
        uses: actions/checkout@v3

      - name: Install Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install NPM packages ♾️🕳️
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        run: yarn install

      - name: Git submodules init
        run: git submodule init

      - name: Git submodules update
        run: git submodule update

        # The next step is required to run Puppeteer in headful mode in GitHub Actions.
        # We attempted to configure it in a headless manner,
        # but it fails right from the start when we attempt to locate the current page of the extension.
      - name: Configure the display server
        run: Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &

      - name: Puppeteer Tests 🧑‍🔬
        env:
          ENVIRONMENT: 'testing'
          # Its value is based on the above Display server configuration
          DISPLAY: ':99.0'
          RELAYER_URL: ${{ secrets.RELAYER_URL }}
          CONSTANTS_ENDPOINT: ${{ secrets.CONSTANTS_ENDPOINT }}
          VELCRO_API_ENDPOINT: ${{ secrets.VELCRO_API_ENDPOINT }}
          BROWSER_EXTENSION_DEFAULT_LOG_LEVEL_PROD: ${{ secrets.BROWSER_EXTENSION_DEFAULT_LOG_LEVEL_PROD }}
          BROWSER_EXTENSION_DEFAULT_LOG_LEVEL_DEV: ${{ secrets.BROWSER_EXTENSION_DEFAULT_LOG_LEVEL_DEV }}
          KEYSTORE_ACCOUNTS: ${{ secrets.KEYSTORE_ACCOUNTS }}
          KEYSTORE_KEYSTORE_UID: ${{ secrets.KEYSTORE_KEYSTORE_UID }}
          KEYSTORE_KEYS: ${{ secrets.KEYSTORE_KEYS }}
          KEYSTORE_SECRETS: ${{ secrets.KEYSTORE_SECRETS }}
          KEYSTORE_ONBOARDING_STATUS: ${{ secrets.KEYSTORE_ONBOARDING_STATUS }}
          KEYSTORE_PERMISSION: ${{ secrets.KEYSTORE_PERMISSION }}
          KEYSTORE_SELECTED_ACCOUNT: ${{ secrets.KEYSTORE_SELECTED_ACCOUNT }}
          KEYSTORE_TERMSTATE: ${{ secrets.KEYSTORE_TERMSTATE }}
          KEYSTORE_PREVIOUSHINTS: ${{ secrets.KEYSTORE_PREVIOUSHINTS }}
          KEYSTORE_PASS_PHRASE: ${{ secrets.KEYSTORE_PASS_PHRASE }}
          PRIVATE_KEY_LEGACY_ACCOUNT: ${{ secrets.PRIVATE_KEY_LEGACY_ACCOUNT }}
          PHRASE_LEGACY_ACCOUNT: ${{ secrets.PHRASE_LEGACY_ACCOUNT }}
          KEYSTORE_ACCOUNTS_1: ${{ secrets.KEYSTORE_ACCOUNTS_1 }}
          KEYSTORE_KEYSTORE_UID_1: ${{ secrets.KEYSTORE_KEYSTORE_UID_1 }}
          KEYSTORE_KEYS_1: ${{ secrets.KEYSTORE_KEYS_1 }}
          KEYSTORE_SECRETS_1: ${{ secrets.KEYSTORE_SECRETS_1 }}
          KEYSTORE_ONBOARDING_STATUS_1: ${{ secrets.KEYSTORE_ONBOARDING_STATUS_1 }}
          KEYSTORE_PERMISSION_1: ${{ secrets.KEYSTORE_PERMISSION_1 }}
          KEYSTORE_SELECTED_ACCOUNT_1: ${{ secrets.KEYSTORE_SELECTED_ACCOUNT_1 }}
          KEYSTORE_TERMSTATE_1: ${{ secrets.KEYSTORE_TERMSTATE_1 }}
          KEYSTORE_PASS_PHRASE_1: ${{ secrets.KEYSTORE_PASS_PHRASE_1 }}

        run: yarn run test:e2e:web
